global:
  scrape_interval: "5s"

scrape_configs:
  - job_name: "api-microservices"
    metrics_path: "/actuator/prometheus"
    eureka_sd_configs:
      - server: http://host.docker.internal:8761/eureka
    